### PR TITLE
First attempt to verify connections and pull process

### PR DESCRIPTION
**Pull request by jas58**

### CODE REVIEW

**Comment by jas58** [comment]
Not sure what went wrong yesterday.  I'm trying more green buttons on Github after learning (20 min ago) that I hadn't completed last week's lessons.  long story.

**Comment by jas58** [comment]
what do I do now?

**Comment by jas58** [comment]
This is feeling more like a circle.

**Comment by jas58** [comment]
This time I noticed the "only those with write access can merge pull requests" announcement.  I'm wondering how that compares to what I saw last week in the branching/forking labs.  Did I not invite @chrisdaaz as an editor?  Did I miss a different step?  I'll keep looking tomorrow.

**Comment by chrisdaaz** [comment]
Hi @jas58 ,

This assignment doesn't require a pull request. Here are the instructions (from Moodle):

>Follow the steps in [this tutorial](https://chrisdaaz.github.io/static-web-scholcomm/tutorials/github/) to test GitHub Actions and GitHub Pages on your own GitHub repository. When you're done, submit the following to complete the lab assignment:
>
>Send me a link to demonstration OER textbook you made, or the GitHub repository you forked as part of the tutorial.
Write a paragraph or more with potential ideas about how you might use GitHub Actions or GitHub Pages in your final project. You are not committing to use either in any specific way, but think about the possibilities and the instructor will help you pursue those ideas if possible. 

I can see that you've done the tutorial successfully (looks great!): https://jas58.github.io/minibookdown/

Now I just need the "paragraph or more" submitted via Moodle.

**Pull request closed without merging**
